### ISSUE TITLE
代码块行号显示异常

### ISSUE THREAD

**Issue by demodeom** [esappear/hexo-theme-clover#14]
![深度截图_选择区域_20191007204808](https://user-images.githubusercontent.com/37200139/66312769-d1982300-e943-11e9-962f-8a0c39290f16.png)

**Comment by esappear** [comment]
https://github.com/esappear/hexo-theme-clover#code-highlight
![image](https://user-images.githubusercontent.com/13843099/67155744-540ee280-f347-11e9-9b90-3d2980f413b3.png)
