### ISSUE TITLE
 npm install hexo-renderer-sass --save error

### ISSUE THREAD

**Issue by jc-Liiiii** [esappear/hexo-theme-clover#17]
In file included from ../src/binding.cpp:3:
../src/sass_context_wrapper.h:8:10: fatal error: 'sass/context.h' file not found
#include <sass/context.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/lee/hexo/ljc/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/lee/hexo/ljc/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/lee/hexo/ljc/node_modules/node-sass
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lee/.npm/_logs/2020-01-01T13_51_06_245Z-debug.log

————————————————————————————————————————————

2020-01-01T13_51_06_245Z-debug.log

3525 verbose stack Error: node-sass@4.13.0 postinstall: `node scripts/build.js`
3525 verbose stack Exit status 1
3525 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
3525 verbose stack     at emitTwo (events.js:126:13)
3525 verbose stack     at EventEmitter.emit (events.js:214:7)
3525 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
3525 verbose stack     at emitTwo (events.js:126:13)
3525 verbose stack     at ChildProcess.emit (events.js:214:7)
3525 verbose stack     at maybeClose (internal/child_process.js:925:16)
3525 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
3526 verbose pkgid node-sass@4.13.0
3527 verbose cwd /Users/lee/hexo/ljc
3528 verbose Darwin 17.7.0
3529 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "hexo-renderer-sass" "--save"
3530 verbose node v8.11.4
3531 verbose npm  v6.13.4
3532 error code ELIFECYCLE
3533 error errno 1
3534 error node-sass@4.13.0 postinstall: `node scripts/build.js`
3534 error Exit status 1
3535 error Failed at the node-sass@4.13.0 postinstall script.
3535 error This is probably not a problem with npm. There is likely additional logging output above.
3536 verbose exit [ 1, true ]

**Comment by eq1024** [comment]
弄好了吗  我也这样子的
