### ISSUE TITLE
样式好像有些问题，代码不支持高亮，表格样式没有啥效果

### ISSUE THREAD

**Issue by luozhix** [esappear/hexo-theme-clover#4]
作者能作下优化吗？

**Comment by NathanDai** [comment]
表格样式不能显示，能不能优化一下

**Comment by esappear** [comment]
已经加上了。
高亮记得在.config.yml文件如下设置：
```
highlight:
  enable: false
```
并在使用的地方声明代码的语言。
效果可见：https://esappear.github.io/clover/2019/09/14/code-highlight/
