### ISSUE TITLE
日期格式与标题大小

### ISSUE THREAD

**Issue by ghost** [esappear/hexo-theme-clover#5]
你好，我使用了这个主题，很简洁，很好看。但是，有两个问题。
1.我要如何更改日期的格式？默认为月-日-年，我想改为年-月-日；
2.自己的名字，就是那个“clover yuan”，在电脑上大小比较合适，但是在手机上显得有点大，我应该怎么改呢？

**Comment by esappear** [comment]
1. 在/layout/_partial/article.ejs 文件中将`<p class="sub"><%- date(post.date, 'MMM D, YYYY') %></p>`修改成`<p class="sub"><%- date(post.date, 'YYYY-MM-DD') %></p>`
2. 在 /source/css/_partial/nav.scss 添加下媒介查询。
